Needs -lm for fabs() in src/gvcmeas.c
/usr/bin/ld.bfd: ./obj/gvcmeas.o: undefined reference to symbol 'fabs@@GLIBC_2.2.5'
/usr/bin/ld.bfd: /usr/lib64/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status